
name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      statuses: write
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory "test-results"
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: "test-results.trx"
          path: test-results/test-results.trx
        if: ${{ always() }}
      - name: Test summary
        uses: dorny/test-reporter@v1
        with:
          name: "Unit Tests"                  
          path: 'test-results/test-results.trx'
          reporter: dotnet-trx
        if: ${{ always() }}
