name: Release

on:
  workflow_dispatch:
  push:
    paths:
     - NextValue/*
    branches:
    - "main"

env:
  VERSION_NUMBER: ${{ format('0.0.{0}{1}', github.run_number, github.ref != 'refs/heads/main' && '-preview' || '-beta')}}
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Package
        run: dotnet pack --configuration Release --no-restore --p:Version=${{env.VERSION_NUMBER}} --output .
      - name: Create Tag
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}  
          script: |
            const {VERSION_NUMBER} = process.env          
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${VERSION_NUMBER}`,
                sha: context.sha
            })
      - name: Publish to NuGet
        run: nuget push NextVersion${{env.VERSION_NUMBER}}.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}      